### ISSUE TITLE
SP Materials cause game crash, possible unwanted munge behaviour?

### ISSUE THREAD

**Issue by DoctorAnsem** [SleepKiller/shaderpatch#34]
Having a lot of trouble getting material system to work. The non-shaderpatch copy of the world works fine, but the SP world crashes very shortly on the loadscreen after the effect system activates. Log does not report back anything of value except the following;

Texture 'tat_bldg_moisturefarm_1_bump' [c21d5bb0] uses 1.33 MB

This is why I have the hunch that there is foul play in the munge process (for lack of better words). This _bump texture is the normal map I've assigned to the stock world, as such it's in the stock_textures folder. The normal map I assigned for shaderpatch is marked with the _normal tag instead. The point is, the _bump version of this texture shouldn't exist in the SP world, should it? It isn't assigned to any of the SP materials. It is, of course, being called by a mesh using Rendertype 28 (yes the stock texture contains a specular map) so that might be why it's getting munged at all in the first place. 

I haven't got a clue if these two issues are actually connected though... any ideas? I tested the Mygeeto SP demo and it worked so it shouldn't be a hardware issue on my end at least.

**Comment by SleepKiller** [comment]
Darn, sorry you're encountering this. Although these tools have existed for some time now they have little use out in the wild and may not be as bug free (or as easy to use as they should be) as a result.

I don't think it'll be directly related to that texture. But I will explain why it is being included. Currently `material_munge` copies and edits `.model` files to make sure the it'll be drawn in the why the custom materials system expects. What it doesn't do (but could in the future) is remove references to unused textures from the `.model.req` file. It is probably worth looking to making that change in order to save space in the final `.lvl` but currently the extra unused textures are fairly harmless. Anyway back onto the main problem.

So first I'd check out if "shader patch.log" (in your "GameData" folder) has anything in it. As you can probably guess from the name this file is where SP's errors get logged to. Sorry if you'd already done this!

Next my ~~excellent~~ **highly questionable** documentation habits may have caused a problem here. My (undocumented) goal is to guarantee that any version of SP can loads files targeting any previous version but old versions can't load files targeting newer versions. In practice what this means is that if you use the mungers from a v0.10 alpha the resulting world won't work on v0.9. (I.e will cause SP to log "Unexpected <Resource Type> version" and terminate.)

The only thing you really need to make sure of here is that when munging your map you're using the mungers from the latest stable release of SP. And when you're playing a SP enabled map (as it were) you're once again using the latest stable release of SP.

Finally it is possible you've found a bug in the tools or the munge script. How comfortable would you be with zipping up your "data_MOD" and (privately, of course) sending it to me? Or better yet if you can get a simple test map to display the issue that'd be great to have instead.

**Comment by SleepKiller** [comment]
Yeah GitHub doesn't appear to have such a feature. If you're on [ModDB](https://www.moddb.com/members/sleepkiller), [GameToast](http://gametoast.com/memberlist.php?mode=viewprofile&u=7772) or [SWBFGamers](https://www.swbfgamers.com/index.php?action=profile;u=1581) the easiest way is probably to just contact me using one of those.

**Comment by DoctorAnsem** [comment]
Alright, I sent you a message on ModDB. Hopefully the issue will not be too elusive lol.

**Comment by DoctorAnsem** [comment]
I think I have come across another issue with the munge files. I wanted to test another map to see if the materials would crash that one too, but I can't get the SP world to pack up at all - it seems that lvlpack might be ignoring something crucial? The stock world is packed up fine. What I did was make just a few PBR materials (is this a problem btw? I don't remember seeing any note on if using SP materials is an all-or-nothing kind of deal) and the munge log states the following:

Error occured while packing "DES.req"
   Unexpected empty REQN section.

DES being the master req file of course. I don't have any idea what the root of the issue is though, other than it possibly wants something to have an SP-edited munged file even though there isn't one? I tried the good old-fashioned copy & paste technique to try and trick lvlpack into thinking the SP munged folder has everything it needs but it didn't work either.

**Comment by DoctorAnsem** [comment]
Alrighty, just in case you hadn't already tracked down what caused this crash, I have. It's a problem in the munge process - animation banks aren't getting packed in and as such the Sarlacc tentacle object caused the map to crash. It's a consistent issue across all animated models.

**Comment by SleepKiller** [comment]
Ah, that's really interesting! Thanks for letting me know, that really narrows the search space for the bug.
