### ISSUE TITLE
Request: making pbr.emissive compatible with "-vertexlighting" tagged models?

### ISSUE THREAD

**Issue by DoctorAnsem** [SleepKiller/shaderpatch#37]
Just something that came up when I tried to add some decoration to one of many indoor areas. It turns out if a vertex lit model uses an emissive material, the albedo map will not be drawn at all, and the emissive material also ignores the "StaticallyLit" flag in the material file itself. (Not to mention emissive material ignores vertex colors, which are at times rather important for the model)

https://i.imgur.com/SuqxJGO.png

This is one case, of course. However, there are several models in the Cloud City map that will call for the same texture (ergo, material) for both interior and exterior areas, and they contain the emissive ceiling lights so it's going to provide a problem soon enough. The carbon freezing chamber is going to need emissive statically lit materials too. Would it be too much of a hassle to make these kinds of setups work in the future?

**Comment by Calrissian97** [comment]
Just to comment on the photo: wow!

**Comment by SleepKiller** [comment]
`pbr` materials ignoring vertex colours is intentional as they almost always carry simple baked lighting information and there is no good way to apply it over a `pbr` material. After [v0.10](https://github.com/SleepKiller/shaderpatch/projects/3) is done I plan to work on creating an easy way to bake high quality lighting for maps that will be usable with `pbr` materials. Does that sound like it would solve your problem?

One thing I could do fairly easily is create a `normal_ext.emissive` rendertype. `normal_ext` materials do respect vertex colours so that could be a solution as well. Do you think a `normal_ext.specular.emissive` rendertype could be a quick temporary solution to the problem?

**Comment by DoctorAnsem** [comment]
I suppose so, yeah. The thing with the Cloud City map is that it has vertex colors almost literally everywhere, simulating light crossfading, interiors.. some models even use it for ambient occlusion. It would need a massive rework if that possibility wasn't there at all anymore. If any functionality that replicates the same effect can be reasonably used and implemented, I'm willing to give it a try.

**Comment by SleepKiller** [comment]
In [v1.0.0](https://github.com/SleepKiller/shaderpatch/releases/tag/v1.0.0-rc.0) `normal_ext` now supports emissive maps. That's as good as I can do for now I'm afraid, hopefully at some point in the future we'll get that hypothetical lightmap baking.
