### ISSUE TITLE
Diffuse textures going missing

### ISSUE THREAD

**Issue by DoctorAnsem** [SleepKiller/shaderpatch#40]
![missing diffuse](https://user-images.githubusercontent.com/45246040/52487069-713ebf00-2bc5-11e9-8f61-9a70a4cf46bb.png)

So back in business, and with something I haven't seen happen yet. It's pretty self-explanatory, but in short the diffuse map isn't getting drawn even though the material and all its textures are reported as being successfully loaded in SP log. The more curious thing is, this material used to be rendered correctly but after I added more SP materials (majority using normal_ext, some using the specular extension) the diffuse map vanished. The issue is consistent across reloading the map. Is it running out of texture memory?

Also a bit unrelated but it's been bugging me. I've noticed normal_ext materials tend to be somewhat darker than their stock counterparts. (PBR materials even darker I think) Is this normal?

**Comment by SleepKiller** [comment]
I'm only speculating here but it looks like `material_munge` has been stupid and not updated the model correctly for use with custom materials. The good news in the next release (which I hope to actually drop this weekend) `material_munge` has already been made smarter to avoid exactly this kind of problem.

> Also a bit unrelated but it's been bugging me. I've noticed normal_ext materials tend to be somewhat darker than their stock counterparts. (PBR materials even darker I think) Is this normal?

Maybe especially if you're using HDR rendering, since rendering in linear color space will give different (more correct) results. Without doing a side-by-side comparison I couldn't be sure. I'd just make sure all your diffuse/albedo textures have there `sRGB` flag set correctly. (It should be set to `yes` for HDR rendering.)

**Comment by DoctorAnsem** [comment]
> The good news in the next release (which I hope to actually drop this weekend) `material_munge` has already been made smarter to avoid exactly this kind of problem.

Will this particular update also fix the problem where character models with custom materials completely break during munge?

**Comment by SleepKiller** [comment]
Should've been fixed in [v1.0.0](https://github.com/SleepKiller/shaderpatch/releases/tag/v1.0.0-rc.0). Again let me know if it hasn't been.
