### ISSUE TITLE
Some questions regarding the various specular effects

### ISSUE THREAD

**Issue by DoctorAnsem** [SleepKiller/shaderpatch#41]
I might have misunderstood some things gravely, but in case there's something going on with the material system, let's just get it over with.

First: normal_ext.specular feels like it might not be obeying the specular map. (supposed to be in the normal map's alpha, with premultiply off and BC3 compression type, correct?) The specular spots are always extremely bright even with a specular exponent of 300, which obviously doesn't make sense in a lot of places. I didn't try fiddling with GlossMapWeight but chances are I don't want it to be anything other than 1.0.

Second: The PBR specular effect is really not making sense to me. The material controls, Metallicness and Roughness scalers, don't seem to do anything. What really bothers me is that according to all the PBR tutorials, Metallicness map should generally be nearly black and white, with only transitions being gray. They also tell Roughness map is what would more commonly be the more traditional specular map equivalent, except inverted. Is this the case with SP PBR or am I missing something? The wiki says Metallicness should go in the red channel and Roughness in the green so that's what I've done. The ingame effects aren't as I expected though; there is no specular shine at all if there is no Metallicness, and with minimal Roughness the surface starts randomly sparkling which is not exactly what I was trying to get from it lol.

So, elephant in the room. Are these problems with SP, or did I screw something up?

**Comment by SleepKiller** [comment]
Okay first I'll get this out of the way.

> So, elephant in the room. Are these problems with SP, or did I screw something up?

I'm, uh, bad at math, like **really** bad so it is possible I screwed up somewhere in the PBR implementation and it is a problem with SP. I hope it isn't but it is a genuine possibility.

> First: normal_ext.specular feels like it might not be obeying the specular map. (supposed to be in the normal map's alpha, with premultiply off and BC3 compression type, correct?) The specular spots are always extremely bright even with a specular exponent of 300, which obviously doesn't make sense in a lot of places. I didn't try fiddling with GlossMapWeight but chances are I don't want it to be anything other than 1.0.

You're right on for the texture format and config. (Although soon in the next release you'll be able to switch it over to BC7 and enjoy higher quality at no extra storage cost.) Now the specular exponent doesn't actually control the brightness of the spot (the source light and specular color do) it controls the focus of the spot (more or less) lower values spread the specular out more while tighter values focus it more.

The way to solve this problem is by lowering the `SpecularColor`. This parameter is actually not unique (although it must be supplied separately) to `normal_ext` and exists on stock materials as well. A lot of stock models (that use specular lighting) do not use a specular color of  `[1, 1, 1]` likely for this exist reason, it can be too bright. Try using a value of  `[0.5, 0.5, 0.5]` and see if it makes a difference. 

If nothing truly makes a difference (even setting the specular map to almost all black) then it is likely this is a problem on SP's end and it'll need looking into.

> Second: The PBR specular effect is really not making sense to me. The material controls, Metallicness and Roughness scalers, don't seem to do anything. What really bothers me is that according to all the PBR tutorials, Metallicness map should generally be nearly black and white, with only transitions being gray. They also tell Roughness map is what would more commonly be the more traditional specular map equivalent, except inverted. Is this the case with SP PBR or am I missing something? The wiki says Metallicness should go in the red channel and Roughness in the green so that's what I've done. The ingame effects aren't as I expected though; there is no specular shine at all if there is no Metallicness

I'm going to ignore metallicness for now and just focus on doing my best to roughly explain roughness. In case you didn't already know it (more or less) [everything is shiny](http://filmicworlds.com/blog/everything-is-shiny/). The roughness of a surface basically controls how clear the reflection of light is off a surface. The rougher the surface the less clear and more spread out the reflection of the light is. Inversely the smoother the surface the more focused and clear the reflection of the light is. 

A roughness value of `0.2` (0x333333 in RGB hexadecimal) should be close(ish) in shininess to a classic Blinn-Phong specular material with an exponent of `64.0`. Fiddle around with values from `0.2` to `0.5` and see if it gives you what you want. It should be simple to use the Levels tool in your image editor of choice to adjust the roughness map's range and test out a bunch of different values.

Metallicness is a bit of a different beast, but I'd become acquainted with authoring roughness maps first before worrying about it. Just leave it at `0.0` (black). 

You can find a visual reference for picking roughness values you can check out [this](https://github.khronos.org/glTF-WebGL-PBR/). Just set the model to `MetalRoughSpheres`. 

Let me know if you do see wild differences in the way SP handles PBR vs other implementations (like the WebGL one above), as I said at the start it is possible there is some problem with it somewhere. 

> and with minimal Roughness the surface starts randomly sparkling which is not exactly what I was trying to get from it lol.
Sounds like that might be a specular aliasing problem. The good news is the next release will have the ability to apply [specular anti-aliasing](https://github.com/SleepKiller/shaderpatch/issues/21) to roughness maps to counteract it to a degree.

**Comment by DoctorAnsem** [comment]
Alright yeah, I'm pretty sure the specular map in normal_ext isn't being obeyed very well. I posted a screenshot before in #39 in which there is a massive specular shine on the rough stone surface even though the alpha channel is almost exclusively black. It's the one in the upper screen. 

From the looks of it, I think I've applied the roughness stuff just as I'd want it, it must be that sparkly look that threw me off. It's rather intense. 

https://i.imgur.com/x2l3KlU.mp4

**Comment by DoctorAnsem** [comment]
Wait a minute... I just took a closer look at that Mygeeto reference map. Could it be my normal maps are wrong and that's why things aren't looking as they should? I noticed you've made yours with _both_ X and Y inverted, and it hit me that on my PBR material maps the normals were indeed facing the wrong way compared to the stock ones. (SP made all the stock normal maps require inverted Y but not X, so that's what all my 1000+ normal maps are standardized as)

...also, that last point. Was it an intentional choice to make stock normals need inverted Y? Because they never had any inverted vectors at the very stock level so SP effectively reads them as upside down. I swear if I changed over 1000 normal maps to accommodate for an oversight, I'm going to tilt xd

**Comment by SleepKiller** [comment]
Sorry, I think that was a mistake on my part. Tangent space is all very confusing to me. I'd hold out just a little bit longer and see how your normal maps behave in the next version with it's updated tangent space. (It's _very_ close to coming out now.) 

If need be I can add an option to `.tex` files to let you invert the XY channels automatically. It's a very simple transform.

**Comment by DoctorAnsem** [comment]
> Let me know if you do see wild differences in the way SP handles PBR vs other implementations

So I took a little bit of a test round regarding this, I loaded my stuff in a 3D application called Materialize to see exactly how I would want my materials to look. It turns out the result is drastically different to what I get ingame.

![pbr test](https://user-images.githubusercontent.com/45246040/54479302-0ca9fc00-4824-11e9-9cce-2211aa0bb2b0.png)

This is the result of 0 metallicness and the roughness map (here it's treated as smoothness but details) I've been using all along. It's exactly the kind of reflection I was expecting - the problem is, ingame there's no reflection _at all_, unless there is metallicness and that material is not supposed to be metallic for sure.

**Comment by SleepKiller** [comment]
Yeah sounds about right. I have taken the time to update the PBR implementation for the next release, so hopefully things will be a bit more correct when it drops.

I've also given the `normal_ext` rendertype some new features and bug fixes as well.

**Comment by SleepKiller** [comment]
[v1.0.0](https://github.com/SleepKiller/shaderpatch/releases/tag/v1.0.0-rc.0) is out and *should* have fixed this, but let me know if it hasn't
