### ISSUE TITLE
High spin rate of shields

### ISSUE THREAD

**Issue by Calrissian97** [SleepKiller/shaderpatch#46]
The shields spin rate seems a bit too fast or bugged. Something isn't right.

**Comment by DoctorAnsem** [comment]
Can confirm, the shield effects seem to be universally broken. I captured a bit of footage on it [right here](https://drive.google.com/open?id=1M5aWuQ0fp-8nIW9QUNPiKm1STC9cXkpB).

The most glaring issues appear to be that the shield geometry itself becomes invisible in near scene, and the texture wrapping is wrong because one half of the shield looks stretched af and the other is kind of whatever it wants to be. The LOD stuff was a bit funky in earlier versions too but not this bad, and the texture was correct before too.

**Comment by SleepKiller** [comment]
I've fixed the shields sometimes being drawn almost completely invisible in dfec44f. I'm still unsure what is causing the other issues as they seem to originate from within the game's code. Which makes them particularly hard to track down, since it probably points to Shader Patch providing a slightly different API to what the game expects at some very specific point that is causing it.
