### ISSUE TITLE
HDR Rendering functions like it did in older versions of Shaderpatch

### ISSUE THREAD

**Issue by auri0n** [SleepKiller/shaderpatch#49]
It sounds like you might be removing HDR in the future, but in case you're not I figured I'd report the issue here. Basically, it works like it did prior to version 0.6, I think:

https://i.imgur.com/SNaJh24.mp4

#27 is also back. Hopefully these will be easy fixes, since you've dealt with them before :o

**Comment by SleepKiller** [comment]
This is actually intentional. In previous versions SP used a bit of a hack to try and make HDR rendering on the game's normal mapped surfaces "just work". However it never really worked that great and often just washed out all the detail from the normal maps. 

So now HDR rendering is intended for use just on maps that use custom materials (as they don't suffer from the above problem). But I did make one change that I feel made the removal of this feature irrelevant.

The big advantage (as far I could tell) that HDR rendering on stock maps had was that HDR postprocessing looks a **lot** nicer than LDR postprocessing. So in the latest version I updated the postprocessing to always be done in HDR even if the game isn't being drawn in HDR.

The results (in my eyes) were just as good as the results the previous HDR rendering hack had been getting, if not better (because now the normal maps detail isn't being washed out). As such I don't think there is any real reason to support trying to force HDR rendering onto maps with custom materials.

But obviously I'm open to feedback on the issue, just make sure the new postprocessing for LDR rendered scenes really is insufficient first.

**Comment by auri0n** [comment]
Interesting, I thought that might be the case. The real reason I've always used HDR is that lighting from lasers/explosives looks so much more realistic. This is more a critique of SWBF2 than your shaders, but some surfaces react really unnaturally to light. If you throw grenades inside the cantina on mos eisley, for example, the light looks strangely... dark lol. SWBF1 actually did a much better job at handling lighting, but it's not the end of the world if this can't be fixed. And thanks for the explanation ;)
