### ISSUE TITLE
SP interface doesn't respond always to mouse clicks

### ISSUE THREAD

**Issue by DoctorAnsem** [SleepKiller/shaderpatch#51]
I've listed a few things I've come across.

- Print screen button can't be used, the game crashed on the spot. HDR was enabled when this happened, I forgot to test if it happens without HDR but I did isolate it enough that it is a shader patch issue.
- If shader patch is enabled, Coruscant straight up crashes upon loading.
- A less severe thing, but if the game is in full screen, it seems that the SP interface can't be operated. The cursor is invisible, although it detects if you are hovering over an item. Regardless, nothing can be clicked.

**Comment by SleepKiller** [comment]
All right. I've fixed the screenshot issue in the most recent release. 

Coruscant doesn't crash for me when I load it so I've got no clue what's going on there. But I did fix an issue that was causing crashes during loading some mods, so that me know if that solved or not. Otherwise do you have any mods installed that could be at play here?

Not sure what's going on with the interface for you, that sounds very strange. Does it happen every time?

**Comment by DoctorAnsem** [comment]
Coruscant issue apparently has been resolved now, it was actually just the Clone Wars era for some reason. I do have the Unofficial 1.2 and 1.3 patches installed so who knows what it was, but it's gone for now.

The interface is inoperable whenever I use the main executable; it was actually that way in the v0.10.0-alpha.4 build too, however it worked back in 0.9.1 I believe. The issue is not there when using the modtool executable so I forgot to report it before.

**Comment by SleepKiller** [comment]
I think I've finally managed to replicate this, so a fix will hopefully be on the way. In the meantime a workaround seemed to be just to Alt-Tab and switch to another app and then back into SWBFII.
