### ISSUE TITLE
soldiers with the normal_ext rendertype applied don't fade out correctly after dying

### ISSUE THREAD

**Issue by auri0n** [SleepKiller/shaderpatch#70]
https://i.imgur.com/5MhyF9v.mp4

**Comment by DoctorAnsem** [comment]
Forgot to mention this before, but this same transparency issue seems to apply to PBR as well, as I've seen this consistently happen with dynamic sky objects that use PBR materials.

**Comment by SleepKiller** [comment]
Update on this, looks like the fade for dying soldiers comes from the stock diffuse material colour which is outright unused in the [pbr shader](https://github.com/SleepKiller/shaderpatch/blob/master/assets/core/src/pbr.fx#L78) and mistakenly overwritten instead of blended in the [normal_ext](https://github.com/SleepKiller/shaderpatch/blob/master/assets/core/src/normal_ext.fx#L116) shader.

Both issues will be fixed for the next bug fix release.
